# Pull the Node image from Docker Hub
FROM node:14-slim

# Setting Working Directory
WORKDIR /usr/app

# Copying only package.json
COPY package*.json ./

# Install Dependencies
RUN npm Install

# Copy rest of the code to container
COPY . .

# Run the API on Nodemon
CMD ["npm", "run", "dev"]